// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionMeta = { id: string, label: string, 
/**
 * The shell asks for confirmation before running it.
 */
destructive: boolean, };
