// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Basic facts about this build, shown in About.
 */
export type AppInfo = { name: string, version: string, specVersion: number, };
