// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bytes that are not valid UTF-8, shown as hex.
 */
export type BinaryValue = { len: number, hex: string, };
