// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something a tool needs from the host beyond pure computation, such as
 * inspecting processes. Open set: `<area>.<verb>`, e.g. `process.inspect`.
 */
export type Capability = string;
