// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryInfo } from "./CategoryInfo";
import type { ToolMeta } from "./ToolMeta";

/**
 * Everything the shell needs to build navigation and search.
 */
export type Catalog = { tools: Array<ToolMeta>, categories: Array<CategoryInfo>, };
