// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Navigation group, by id. Open set: a tool (or a later extension) may name
 * a category the host doesn't know. Presentation (label, sidebar position)
 * belongs to the host, not to tools: see [`CategoryInfo`].
 */
export type Category = string;
