// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";

/**
 * How the shell presents a category: sent alongside the tool list.
 */
export type CategoryInfo = { id: Category, 
/**
 * English fallback; the front end translates `category.<id>`.
 */
label: string, 
/**
 * Sidebar position, ascending; unknown categories come last, by id.
 */
order: number, };
