// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Choice } from "./Choice";

export type Control = { "kind": "toggle", default: boolean, } | { "kind": "choice", choices: Array<Choice>, default: string, } | { "kind": "integer", min: number, max: number, default: number, } | { "kind": "text", default: string, 
/**
 * Maximum length in characters.
 */
limit: number, } | { "kind": "unsupported" };
