// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { Severity } from "./Severity";
import type { JsonValue } from "./serde_json/JsonValue";

export type Diagnostic = { severity: Severity, code: ErrorCode, 
/**
 * English fallback; must not echo the input.
 */
message: string, 
/**
 * 1-based.
 */
line: number | null, 
/**
 * 1-based, in UTF-16 code units (what the editor counts).
 */
column: number | null, details: JsonValue | null, };
