// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable error code: `<namespace>.<name>`, where the namespace is `core` or
 * the tool id. The front end translates codes; messages are English fallbacks.
 */
export type ErrorCode = string;
