// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionSpec } from "./OptionSpec";
import type { OutputSpec } from "./OutputSpec";

export type GeneratorSpec = { action: string, options: Array<OptionSpec>, outputs: Array<OutputSpec>, 
/**
 * Run once with default options when the tool opens.
 */
runOnOpen: boolean, };
