// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InputSpec = { 
/**
 * Editor language hint, e.g. `json`; `None` for plain text.
 */
lang: string | null, placeholder: string | null, };
