// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyValueRow = { key: string, value: string, note?: string, 
/**
 * Masked in the UI until revealed; copied through the sensitive path.
 * Always explicit, so a forgotten flag can't silently unmask a value.
 */
secret: boolean, };
