// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Control } from "./Control";

export type OptionSpec = { 
/**
 * Key in the input object; never `input` or `file`.
 */
key: string, label: string, control: Control, 
/**
 * Transform modes this option applies to; empty means all.
 */
modes: Array<string>, };
