// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputKind } from "./OutputKind";

export type OutputSpec = { 
/**
 * Key in the result object.
 */
key: string, label: string, format: OutputKind, };
