// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an output value is shaped and rendered. See `crate::payload`.
 */
export type OutputKind = { "kind": "text" } | { "kind": "code", lang: string, } | { "kind": "key_value" } | { "kind": "diagnostics" } | { "kind": "binary" } | { "kind": "unsupported" };
