// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionMeta } from "./ActionMeta";
import type { Capability } from "./Capability";
import type { Category } from "./Category";
import type { ToolId } from "./ToolId";
import type { UiSpec } from "./UiSpec";

export type ToolMeta = { 
/**
 * `crate::SPEC_VERSION` for built-in tools.
 */
specVersion: number, id: ToolId, 
/**
 * English fallbacks; the front end translates `tool.<id>.name` etc.
 */
name: string, description: string, category: Category, 
/**
 * Extra search terms, lower case.
 */
keywords: Array<string>, 
/**
 * SVG markup checked by `crate::validate_icon`.
 */
icon: string, capabilities: Array<Capability>, actions: Array<ActionMeta>, 
/**
 * Listed in the tray menu.
 */
tray: boolean, ui: UiSpec, };
