// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A tool's failure. `code` is stable and translated by the front end;
 * `message` is an English fallback and never echoes the input.
 */
export type ToolError = { code: ErrorCode, message: string, details: JsonValue | null, };
