// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable tool identifier, equal to the tool's folder name.
 *
 * Grammar: `[a-z][a-z0-9_]*`, at most 64 bytes. Ids containing `__` are
 * reserved for runtime extensions (`<publisher>__<name>`), and `core` is
 * reserved for the host's error codes.
 */
export type ToolId = string;
