// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputSpec } from "./InputSpec";
import type { OptionSpec } from "./OptionSpec";
import type { OutputSpec } from "./OutputSpec";

export type TransformSpec = { 
/**
 * Action ids offered as modes; the first is the default.
 */
modes: Array<string>, input: InputSpec, options: Array<OptionSpec>, outputs: Array<OutputSpec>, 
/**
 * Re-run (debounced) as the input changes.
 */
live: boolean, };
