// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratorSpec } from "./GeneratorSpec";
import type { TransformSpec } from "./TransformSpec";

export type UiSpec = { "kind": "transform" } & TransformSpec | { "kind": "generator" } & GeneratorSpec | { "kind": "custom", view: string, } | { "kind": "unsupported" };
