// Every call into Rust goes through here. Types come from app/src/bindings
// (generated by `cargo xtask bindings`; never edited by hand).
import { Channel, invoke } from '@tauri-apps/api/core';
import type { AppInfo } from '$bindings/AppInfo';
import type { Catalog } from '$bindings/Catalog';
import type { Progress } from '$bindings/Progress';
import type { RunEnvelope } from '$bindings/RunEnvelope';
import type { SearchHit } from '$bindings/SearchHit';
import type { Settings } from '$bindings/Settings';
import type { ToolError } from '$bindings/ToolError';
import type { JsonValue } from '$bindings/serde_json/JsonValue';

export type ToolInput = Record<string, JsonValue>;
export type ToolOutput = Record<string, JsonValue>;

export type RunResult = { ok: true; value: ToolOutput } | { ok: false; error: ToolError };

export interface Run {
  runId: string;
  result: Promise<RunResult>;
  cancel: () => Promise<boolean>;
}

export const getAppInfo = (): Promise<AppInfo> => invoke<AppInfo>('app_info');

/** Tells the shell the first frame is rendered, so the window can be shown. */
export const shellReady = (): Promise<void> => invoke<void>('shell_ready');

export const listTools = (): Promise<Catalog> => invoke<Catalog>('list_tools');

export const searchTools = (query: string): Promise<SearchHit[]> =>
  invoke<SearchHit[]>('search', { query });

/** Copies through Rust; sensitive copies stay out of clipboard history and sync. */
export const copyText = (text: string, sensitive = true): Promise<void> =>
  invoke<void>('copy_text', { text, sensitive });

export const getSettings = (): Promise<Settings> => invoke<Settings>('settings_get');

export const saveSettings = (settings: Settings): Promise<void> =>
  invoke<void>('settings_set', { settings });

/** Runs a tool action. Results of superseded runs should be ignored by the caller. */
export function runTool(
  tool: string,
  action: string,
  input: ToolInput,
  onProgress?: (progress: Progress) => void,
): Run {
  const runId = crypto.randomUUID();
  const progress = new Channel<Progress>();
  if (onProgress) progress.onmessage = onProgress;
  const result = invoke<ArrayBuffer | RunEnvelope>('run_tool', {
    tool,
    action,
    runId,
    input,
    progress,
  }).then(decodeEnvelope, (error: unknown) => ipcFailure(error));
  return { runId, result, cancel: () => invoke<boolean>('cancel_run', { runId }) };
}

/** `run_tool` answers with raw JSON bytes (an ArrayBuffer); mocks may answer with objects. */
export function decodeEnvelope(raw: ArrayBuffer | ArrayBufferView | RunEnvelope): RunResult {
  const envelope: RunEnvelope = isBytes(raw)
    ? (JSON.parse(new TextDecoder().decode(raw)) as RunEnvelope)
    : raw;
  if ('ok' in envelope) return { ok: true, value: envelope.ok as ToolOutput };
  return { ok: false, error: envelope.err };
}

/** Realm-independent: buffers can come from another JS realm (iframes, test runners). */
function isBytes(raw: unknown): raw is ArrayBuffer | ArrayBufferView {
  return (
    raw instanceof ArrayBuffer ||
    ArrayBuffer.isView(raw) ||
    Object.prototype.toString.call(raw) === '[object ArrayBuffer]'
  );
}

function ipcFailure(error: unknown): RunResult {
  return {
    ok: false,
    error: { code: 'core.ipc', message: String(error), details: null },
  };
}
