// Every call into Rust goes through here. Types come from app/src/bindings
// (generated by `cargo xtask bindings`; never edited by hand).
import { Channel, invoke } from '@tauri-apps/api/core';
import type { AppInfo } from '$bindings/AppInfo';
import type { Catalog } from '$bindings/Catalog';
import type { Progress } from '$bindings/Progress';
import type { SearchHit } from '$bindings/SearchHit';
import type { Settings } from '$bindings/Settings';
import type { ToolError } from '$bindings/ToolError';
import type { JsonValue } from '$bindings/serde_json/JsonValue';
import { REPOSITORY_URL } from './links';

export type ToolInput = Record<string, JsonValue>;
/** What generic views get: one value per declared output. */
export type ToolOutput = Record<string, JsonValue>;

/** A tool returns any JSON value; custom views decide its shape. */
export type RunResult = { ok: true; value: JsonValue } | { ok: false; error: ToolError };

export interface Run {
  runId: string;
  result: Promise<RunResult>;
  cancel: () => Promise<boolean>;
}

export const getAppInfo = (): Promise<AppInfo> => invoke<AppInfo>('app_info');

/** Tells the shell the first frame is rendered, so the window can be shown. */
export const shellReady = (): Promise<void> => invoke<void>('shell_ready');

export const listTools = (): Promise<Catalog> => invoke<Catalog>('list_tools');

export const searchTools = (query: string): Promise<SearchHit[]> =>
  invoke<SearchHit[]>('search', { query });

/**
 * Copies through Rust, which always adds the OS's exclusion markers: on Windows
 * the copy stays out of clipboard history, cloud sync and clipboard monitors;
 * on macOS, out of history apps that honour the marker; on Linux, out of
 * Klipper-style clipboard managers.
 */
export const copyText = (text: string): Promise<void> => invoke<void>('copy_text', { text });

export const getSettings = (): Promise<Settings> => invoke<Settings>('settings_get');

export const saveSettings = (settings: Settings): Promise<void> =>
  invoke<void>('settings_set', { settings });

/** Shows Navaja's log folder in the OS file manager. */
export const openLogs = (): Promise<void> => invoke<void>('open_logs');

/** Quits Navaja the way the tray's Quit does. The promise may never settle. */
export const quitApp = (): Promise<void> => invoke<void>('quit');

/** Opens a page of Navaja's repository in the default browser. Rust refuses any other URL. */
export const openUrl = (url: string): Promise<void> => invoke<void>('open_url', { url });

/** Opens the repository's home page in the default browser. */
export const openRepository = (): Promise<void> => openUrl(REPOSITORY_URL);

/** Runs a tool action. Results of superseded runs should be ignored by the caller. */
export function runTool(
  tool: string,
  action: string,
  input: ToolInput,
  onProgress?: (progress: Progress) => void,
): Run {
  const runId = crypto.randomUUID();
  const progress = new Channel<Progress>();
  if (onProgress) progress.onmessage = onProgress;
  const result = invoke<unknown>('run_tool', {
    tool,
    action,
    runId,
    input,
    progress,
  }).then(decodeEnvelope, (error: unknown) => ipcFailure(error));
  return { runId, result, cancel: () => invoke<boolean>('cancel_run', { runId }) };
}

const MALFORMED = 'malformed run_tool response';

/**
 * `run_tool` answers with raw JSON bytes: an ArrayBuffer, or an array of
 * numbers when Tauri falls back to postMessage IPC. Mocks may answer with
 * objects. Anything else becomes a `core.ipc` error, never a silent failure.
 */
export function decodeEnvelope(raw: unknown): RunResult {
  let envelope: unknown = raw;
  try {
    if (Array.isArray(raw)) envelope = parseBytes(Uint8Array.from(raw as number[]));
    else if (isBytes(raw)) envelope = parseBytes(raw);
  } catch {
    // Not the parser's message: it can quote part of the output.
    return ipcFailure(MALFORMED);
  }
  if (isRecord(envelope) && 'ok' in envelope && envelope.ok !== undefined) {
    return { ok: true, value: envelope.ok as JsonValue };
  }
  if (isRecord(envelope) && isToolError(envelope.err)) return { ok: false, error: envelope.err };
  return ipcFailure(MALFORMED);
}

function parseBytes(bytes: ArrayBuffer | ArrayBufferView): unknown {
  return JSON.parse(new TextDecoder().decode(bytes));
}

/** Realm-independent: buffers can come from another JS realm (iframes, test runners). */
function isBytes(raw: unknown): raw is ArrayBuffer | ArrayBufferView {
  return (
    raw instanceof ArrayBuffer ||
    ArrayBuffer.isView(raw) ||
    Object.prototype.toString.call(raw) === '[object ArrayBuffer]'
  );
}

/** Generic views need an object keyed by output; Rust's registry checks that in debug builds. */
export function isToolOutput(value: JsonValue): value is ToolOutput {
  return isRecord(value);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isToolError(value: unknown): value is ToolError {
  return isRecord(value) && typeof value.code === 'string' && typeof value.message === 'string';
}

function ipcFailure(error: unknown): RunResult {
  return {
    ok: false,
    error: { code: 'core.ipc', message: String(error), details: null },
  };
}
