//! `cargo xtask acl`: the resolved ACL snapshot in `app/src-tauri/acl.lock.json`.
//!
//! The snapshot is what the release build lets its webview call: the
//! capabilities `tauri.conf.json` names (not the e2e overlay), resolved with
//! the app's default features by Tauri's own code (`tauri-utils`, pinned to
//! the version `tauri` uses). A new grant then shows up as a reviewed diff
//! of the lock, and `cargo xtask check` fails until that diff is committed.
//!
//! The inputs come from the app crate's build script: tauri-build writes the
//! permission manifests of the app and of every plugin it depends on, and the
//! capability files, into its `OUT_DIR`. `cargo check -p navaja` reruns it
//! when they changed, and its JSON messages name that `OUT_DIR`. The copies
//! in `gen/schemas` are not used: every build overwrites them, the e2e build
//! (with WebdriverIO's plugins) included.

use std::collections::{BTreeMap, BTreeSet};
use std::io::BufReader;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use anyhow::{Context, Result, bail};
use cargo_metadata::{Message, MetadataCommand, PackageId};
use serde::{Deserialize, Serialize};
use tauri_utils::acl::capability::Capability;
use tauri_utils::acl::manifest::Manifest;
use tauri_utils::acl::resolved::{Resolved, ResolvedCommand, ResolvedScope};
use tauri_utils::acl::{
    ACL_MANIFESTS_FILE_NAME, CAPABILITIES_FILE_NAME, ExecutionContext, get_capabilities,
};
use tauri_utils::config::Config;
use tauri_utils::platform::Target;

use crate::util::{cargo, root};

/// The committed snapshot, relative to the repository root.
pub const LOCK: &str = "app/src-tauri/acl.lock.json";
const APP: &str = "navaja";
const CONFIG: &str = "app/src-tauri/tauri.conf.json";

/// The desktop targets Navaja ships on. Capabilities and permissions may be
/// limited to some of them, so each one is resolved.
const TARGETS: [Target; 3] = [Target::Linux, Target::MacOS, Target::Windows];

const COMMENT: &str = "Generated by `cargo xtask acl`: what the release build's webview may call. \
                       Do not edit by hand; review every change.";

/// The resolved ACL in a stable, reviewable form.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Snapshot {
    #[serde(rename = "$comment")]
    comment: String,
    /// Whether Tauri checks the app's own commands at all. Without an app
    /// manifest (commands declared in build.rs) every app command is allowed.
    app_commands_checked: bool,
    /// Command (`plugin:<name>|<command>` for plugins) -> who may call it.
    allowed: BTreeMap<String, Vec<Grant>>,
    /// Commands denied explicitly; a denial wins over any grant.
    denied: BTreeMap<String, Vec<Grant>>,
    /// Plugin -> scopes that apply to all of its commands.
    global_scopes: BTreeMap<String, Vec<Scope>>,
}

/// One grant of a command: where calls may come from, and its scope.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Grant {
    /// `local` (the app's own pages) or `remote <URL pattern>`.
    context: String,
    windows: Vec<String>,
    webviews: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    scope: Option<Scope>,
    platforms: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Scope {
    allow: Vec<serde_json::Value>,
    deny: Vec<serde_json::Value>,
    /// Empty inside a grant, which carries its own platforms.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    platforms: Vec<String>,
}

/// `cargo xtask acl`: resolves the ACL afresh and writes the lock.
pub fn run() -> Result<()> {
    let root = root();
    let fresh = render(&resolve_fresh(&root)?)?;
    let path = root.join(LOCK);
    std::fs::write(&path, fresh).with_context(|| format!("writing {}", path.display()))?;
    println!("{LOCK} written; review its diff before committing");
    Ok(())
}

/// For `cargo xtask check`: how the committed lock differs from a fresh
/// resolution, if it does.
pub fn problems(root: &Path) -> Result<Vec<String>> {
    let fresh = resolve_fresh(root)?;
    let path = root.join(LOCK);
    let committed = match std::fs::read_to_string(&path) {
        Ok(text) => text.replace("\r\n", "\n"),
        Err(error) => {
            return Ok(vec![format!(
                "{LOCK} cannot be read ({error}); run `cargo xtask acl` and review the result"
            )]);
        }
    };
    let mut problems = compare(&committed, &fresh)?;
    if !problems.is_empty() {
        problems.push(format!(
            "{LOCK} is out of date: run `cargo xtask acl` and review the diff before committing it"
        ));
    }
    Ok(problems)
}

/// Builds the app crate's build script with default features and resolves
/// the ACL from what it wrote.
fn resolve_fresh(root: &Path) -> Result<Snapshot> {
    let out_dir = app_out_dir(root)?;
    let manifests: BTreeMap<String, Manifest> = read_json(&out_dir.join(ACL_MANIFESTS_FILE_NAME))?;
    let from_files: BTreeMap<String, Capability> =
        read_json(&out_dir.join(CAPABILITIES_FILE_NAME))?;
    let config: Config = read_json(&root.join(CONFIG))?;
    // The same selection tauri-codegen makes: the capabilities the config
    // names (or all of them if it names none), plus inline ones.
    let capabilities = get_capabilities(&config, from_files, None)
        .context("selecting the capabilities tauri.conf.json names")?;
    snapshot(&manifests, &capabilities)
}

/// The app crate's `OUT_DIR`, after `cargo check -p navaja` (default
/// features) has brought its build script up to date.
fn app_out_dir(root: &Path) -> Result<PathBuf> {
    let metadata = MetadataCommand::new()
        .manifest_path(root.join("Cargo.toml"))
        .no_deps()
        .exec()
        .context("cargo metadata")?;
    let app: PackageId = metadata
        .workspace_packages()
        .into_iter()
        .find(|p| p.name.as_str() == APP)
        .map(|p| p.id.clone())
        .context("the app crate is not in the workspace")?;

    let mut child = Command::new(cargo())
        .current_dir(root)
        .args([
            "check",
            "--package",
            APP,
            "--message-format=json-render-diagnostics",
        ])
        // The Tauri CLI passes `--config` overlays through this variable;
        // the snapshot is of tauri.conf.json alone.
        .env_remove("TAURI_CONFIG")
        .stdout(Stdio::piped())
        .spawn()
        .context("running cargo check for the app crate")?;
    let stdout = child.stdout.take().context("cargo check has no stdout")?;
    let mut out_dir = None;
    for message in Message::parse_stream(BufReader::new(stdout)) {
        if let Message::BuildScriptExecuted(script) = message.context("reading cargo output")?
            && script.package_id == app
        {
            out_dir = Some(script.out_dir.into_std_path_buf());
        }
    }
    let status = child.wait().context("waiting for cargo check")?;
    if !status.success() {
        bail!("cargo check -p {APP} failed ({status})");
    }
    out_dir.context("cargo check did not report the app's build script")
}

fn read_json<T: serde::de::DeserializeOwned>(path: &Path) -> Result<T> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    serde_json::from_str(&text).with_context(|| format!("parsing {}", path.display()))
}

/// Resolves the ACL for every desktop target and merges the results: an
/// entry that is the same on several targets appears once, listing them.
pub fn snapshot(
    manifests: &BTreeMap<String, Manifest>,
    capabilities: &BTreeMap<String, Capability>,
) -> Result<Snapshot> {
    let mut allowed = Merged::default();
    let mut denied = Merged::default();
    let mut global = Merged::default();
    let mut app_commands_checked = false;
    for target in TARGETS {
        let resolved = Resolved::resolve(manifests, capabilities.clone(), target)
            .with_context(|| format!("resolving the ACL for {target}"))?;
        let platform = platform_name(target)?;
        app_commands_checked |= resolved.has_app_acl;
        for (command, grants) in &resolved.allowed_commands {
            for grant in grants {
                allowed.add(
                    command,
                    grant_of(grant, &resolved.command_scope)?,
                    &platform,
                )?;
            }
        }
        for (command, grants) in &resolved.denied_commands {
            for grant in grants {
                denied.add(
                    command,
                    grant_of(grant, &resolved.command_scope)?,
                    &platform,
                )?;
            }
        }
        for (plugin, scope) in &resolved.global_scope {
            global.add(plugin, scope_of(scope), &platform)?;
        }
    }
    Ok(Snapshot {
        comment: COMMENT.to_owned(),
        app_commands_checked,
        allowed: allowed.finish(|mut grant, platforms| {
            grant.platforms = platforms;
            grant
        }),
        denied: denied.finish(|mut grant, platforms| {
            grant.platforms = platforms;
            grant
        }),
        global_scopes: global.finish(|mut scope, platforms| {
            scope.platforms = platforms;
            scope
        }),
    })
}

/// Entries per key, each with the platforms it was resolved on. Entries are
/// told apart, and sorted, by their canonical JSON.
struct Merged<T> {
    entries: BTreeMap<String, BTreeMap<String, (T, BTreeSet<String>)>>,
}

impl<T> Default for Merged<T> {
    fn default() -> Self {
        Self {
            entries: BTreeMap::new(),
        }
    }
}

impl<T: Serialize> Merged<T> {
    fn add(&mut self, key: &str, entry: T, platform: &str) -> Result<()> {
        let canonical = serde_json::to_string(&entry)?;
        self.entries
            .entry(key.to_owned())
            .or_default()
            .entry(canonical)
            .or_insert_with(|| (entry, BTreeSet::new()))
            .1
            .insert(platform.to_owned());
        Ok(())
    }

    fn finish(self, with_platforms: impl Fn(T, Vec<String>) -> T) -> BTreeMap<String, Vec<T>> {
        self.entries
            .into_iter()
            .map(|(key, entries)| {
                let list = entries
                    .into_values()
                    .map(|(entry, platforms)| {
                        with_platforms(entry, platforms.into_iter().collect())
                    })
                    .collect();
                (key, list)
            })
            .collect()
    }
}

/// Tauri's own spelling of a target, as capabilities write it.
fn platform_name(target: Target) -> Result<String> {
    match serde_json::to_value(target)? {
        serde_json::Value::String(name) => Ok(name),
        other => bail!("unexpected target name {other}"),
    }
}

fn grant_of(command: &ResolvedCommand, scopes: &BTreeMap<u64, ResolvedScope>) -> Result<Grant> {
    let context = match &command.context {
        ExecutionContext::Local => "local".to_owned(),
        ExecutionContext::Remote { url } => format!("remote {}", url.as_str()),
    };
    let mut windows: Vec<String> = command
        .windows
        .iter()
        .map(|p| p.as_str().to_owned())
        .collect();
    let mut webviews: Vec<String> = command
        .webviews
        .iter()
        .map(|p| p.as_str().to_owned())
        .collect();
    windows.sort();
    webviews.sort();
    let scope = match command.scope_id {
        None => None,
        Some(id) => Some(scope_of(
            scopes
                .get(&id)
                .context("a command refers to a missing scope")?,
        )),
    };
    Ok(Grant {
        context,
        windows,
        webviews,
        scope,
        platforms: Vec::new(),
    })
}

fn scope_of(scope: &ResolvedScope) -> Scope {
    let values = |list: &[tauri_utils::acl::Value]| {
        let mut values: Vec<serde_json::Value> =
            list.iter().cloned().map(serde_json::Value::from).collect();
        values.sort_by_cached_key(serde_json::Value::to_string);
        values
    };
    Scope {
        allow: values(&scope.allow),
        deny: values(&scope.deny),
        platforms: Vec::new(),
    }
}

/// Pretty-printed JSON with a trailing newline. Keys and lists are already
/// sorted, so equal ACLs render to equal bytes.
pub fn render(snapshot: &Snapshot) -> Result<String> {
    let mut text = serde_json::to_string_pretty(snapshot)?;
    text.push('\n');
    Ok(text)
}

/// Differences between the committed lock and a fresh snapshot, by command
/// where possible.
fn compare(committed: &str, fresh: &Snapshot) -> Result<Vec<String>> {
    let rendered = render(fresh)?;
    if committed == rendered {
        return Ok(Vec::new());
    }
    let old: Snapshot = match serde_json::from_str(committed) {
        Ok(old) => old,
        Err(error) => return Ok(vec![format!("{LOCK} is not a valid snapshot: {error}")]),
    };
    let mut problems = Vec::new();
    if old.app_commands_checked != fresh.app_commands_checked {
        problems.push(format!(
            "app commands checked by the ACL: {} in the lock, {} now",
            old.app_commands_checked, fresh.app_commands_checked
        ));
    }
    diff_section(
        "allowed command",
        &old.allowed,
        &fresh.allowed,
        &mut problems,
    );
    diff_section("denied command", &old.denied, &fresh.denied, &mut problems);
    diff_section(
        "global scope of",
        &old.global_scopes,
        &fresh.global_scopes,
        &mut problems,
    );
    if problems.is_empty() {
        problems.push(format!(
            "{LOCK} has the same ACL but not in the canonical form"
        ));
    }
    Ok(problems)
}

fn diff_section<T: PartialEq>(
    what: &str,
    old: &BTreeMap<String, Vec<T>>,
    new: &BTreeMap<String, Vec<T>>,
    problems: &mut Vec<String>,
) {
    for (key, entries) in new {
        match old.get(key) {
            None => problems.push(format!("{what} `{key}` is not in the lock")),
            Some(previous) if previous != entries => {
                problems.push(format!("{what} `{key}` differs from the lock"));
            }
            Some(_) => {}
        }
    }
    for key in old.keys().filter(|key| !new.contains_key(*key)) {
        problems.push(format!(
            "{what} `{key}` is in the lock but no longer resolved"
        ));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// The app's manifest as tauri-build writes it for `commands`.
    fn app_manifest(commands: &[&str]) -> Manifest {
        let permissions: serde_json::Map<String, serde_json::Value> = commands
            .iter()
            .map(|command| {
                let id = format!("allow-{}", command.replace('_', "-"));
                let permission = json!({
                    "identifier": id,
                    "commands": { "allow": [command], "deny": [] },
                });
                (id, permission)
            })
            .collect();
        serde_json::from_value(json!({
            "default_permission": null,
            "permissions": permissions,
            "permission_sets": {},
            "global_scope_schema": null,
        }))
        .unwrap()
    }

    /// A plugin with a scoped command and a global scope.
    fn plugin_manifest() -> Manifest {
        serde_json::from_value(json!({
            "default_permission": null,
            "permissions": {
                "allow-open": {
                    "identifier": "allow-open",
                    "commands": { "allow": ["open"], "deny": [] },
                    "scope": { "allow": [{ "url": "https://b.example/*" }, { "url": "https://a.example/*" }] },
                },
                "deny-open": {
                    "identifier": "deny-open",
                    "commands": { "allow": [], "deny": ["open"] },
                },
                "home": {
                    "identifier": "home",
                    "commands": { "allow": [], "deny": [] },
                    "scope": { "allow": ["$HOME/*"] },
                    "platforms": ["linux"],
                },
            },
            "permission_sets": {},
            "global_scope_schema": null,
        }))
        .unwrap()
    }

    fn manifests(commands: &[&str]) -> BTreeMap<String, Manifest> {
        BTreeMap::from([
            ("__app-acl__".to_owned(), app_manifest(commands)),
            ("demo".to_owned(), plugin_manifest()),
        ])
    }

    fn capability(id: &str, windows: &[&str], permissions: &[&str]) -> (String, Capability) {
        let capability = serde_json::from_value(json!({
            "identifier": id,
            "windows": windows,
            "permissions": permissions,
        }))
        .unwrap();
        (id.to_owned(), capability)
    }

    const COMMANDS: &[&str] = &["app_info", "quit", "search"];

    fn render_of(capabilities: &[(String, Capability)]) -> String {
        let capabilities = capabilities.iter().cloned().collect();
        render(&snapshot(&manifests(COMMANDS), &capabilities).unwrap()).unwrap()
    }

    #[test]
    fn rendering_is_deterministic_and_sorted() {
        let forward = render_of(&[capability(
            "main",
            &["main", "aux"],
            &["allow-search", "allow-app-info"],
        )]);
        let backward = render_of(&[capability(
            "main",
            &["aux", "main"],
            &["allow-app-info", "allow-search"],
        )]);
        assert_eq!(forward, backward);
        assert!(forward.ends_with("}\n") && !forward.contains('\r'));

        let snapshot: Snapshot = serde_json::from_str(&forward).unwrap();
        assert!(snapshot.app_commands_checked);
        assert_eq!(
            snapshot.allowed.keys().collect::<Vec<_>>(),
            ["app_info", "search"]
        );
        let grant = &snapshot.allowed["search"][0];
        assert_eq!(grant.context, "local");
        assert_eq!(grant.windows, ["aux", "main"]);
        assert_eq!(grant.platforms, ["linux", "macOS", "windows"]);
        assert_eq!(grant.scope, None);
        // Rendering what was parsed gives the same bytes.
        assert_eq!(render(&snapshot).unwrap(), forward);
    }

    #[test]
    fn scopes_denials_and_platforms_are_kept() {
        let text = render_of(&[capability(
            "main",
            &["main"],
            &["demo:allow-open", "demo:deny-open", "demo:home"],
        )]);
        let snapshot: Snapshot = serde_json::from_str(&text).unwrap();
        let scope = snapshot.allowed["plugin:demo|open"][0]
            .scope
            .clone()
            .unwrap();
        // Sorted, whatever order the manifest listed them in.
        assert_eq!(
            scope.allow,
            [
                json!({ "url": "https://a.example/*" }),
                json!({ "url": "https://b.example/*" })
            ]
        );
        assert!(snapshot.denied.contains_key("plugin:demo|open"));
        let home = &snapshot.global_scopes["demo"];
        assert_eq!(home.len(), 1);
        assert_eq!(home[0].allow, [json!("$HOME/*")]);
        assert_eq!(home[0].platforms, ["linux"]);
    }

    #[test]
    fn a_grant_on_some_platforms_lists_them() {
        let (id, mut windows_only) = capability("win", &["main"], &["allow-quit"]);
        windows_only.platforms = Some(vec![Target::Windows]);
        let text = render_of(&[
            capability("main", &["main"], &["allow-app-info"]),
            (id, windows_only),
        ]);
        let snapshot: Snapshot = serde_json::from_str(&text).unwrap();
        assert_eq!(snapshot.allowed["quit"][0].platforms, ["windows"]);
        assert_eq!(
            snapshot.allowed["app_info"][0].platforms,
            ["linux", "macOS", "windows"]
        );
    }

    #[test]
    fn an_extra_granted_command_is_a_difference() {
        let base = [capability("main", &["main"], &["allow-app-info"])];
        let committed = render_of(&base);
        let fresh_text = render_of(&[capability(
            "main",
            &["main"],
            &["allow-app-info", "allow-quit"],
        )]);
        let fresh: Snapshot = serde_json::from_str(&fresh_text).unwrap();
        assert_eq!(
            compare(&committed, &fresh).unwrap(),
            ["allowed command `quit` is not in the lock"]
        );
        // And the other way round.
        let old: Snapshot = serde_json::from_str(&committed).unwrap();
        assert_eq!(
            compare(&fresh_text, &old).unwrap(),
            ["allowed command `quit` is in the lock but no longer resolved"]
        );
        assert!(compare(&committed, &old).unwrap().is_empty());
    }

    #[test]
    fn a_wider_grant_is_a_difference() {
        let committed = render_of(&[capability("main", &["main"], &["allow-app-info"])]);
        let wider = render_of(&[capability("main", &["*"], &["allow-app-info"])]);
        let wider: Snapshot = serde_json::from_str(&wider).unwrap();
        assert_eq!(
            compare(&committed, &wider).unwrap(),
            ["allowed command `app_info` differs from the lock"]
        );
    }

    #[test]
    fn hand_edits_are_reported() {
        let committed = render_of(&[capability("main", &["main"], &["allow-app-info"])]);
        let fresh: Snapshot = serde_json::from_str(&committed).unwrap();
        let reformatted = committed.replace("  ", "    ");
        assert_eq!(
            compare(&reformatted, &fresh).unwrap(),
            [format!(
                "{LOCK} has the same ACL but not in the canonical form"
            )]
        );
        let broken = compare("{", &fresh).unwrap();
        assert!(broken[0].contains("not a valid snapshot"), "{broken:?}");
    }

    #[test]
    fn the_committed_lock_is_canonical() {
        let path = crate::util::root().join(LOCK);
        let text = std::fs::read_to_string(&path)
            .unwrap()
            .replace("\r\n", "\n");
        let snapshot: Snapshot = serde_json::from_str(&text).unwrap();
        assert_eq!(render(&snapshot).unwrap(), text);
        assert!(snapshot.app_commands_checked);
        // The release webview gets local, app-only grants.
        for (command, grants) in &snapshot.allowed {
            assert!(!command.starts_with("plugin:"), "{command}");
            for grant in grants {
                assert_eq!(grant.context, "local", "{command}");
                assert_eq!(grant.windows, ["main"], "{command}");
            }
        }
    }
}
