//! `cargo xtask bindings [--check]`: TypeScript bindings generated by ts-rs.
//!
//! Without `--check`, regenerates `app/src/bindings` from scratch. With it,
//! generates into a temporary directory and fails if anything differs from
//! the committed files.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};

use crate::util::{cargo, report, root};

/// Crates whose `ts` feature exports bindings.
const CRATES: &[&str] = &["navaja-core", "navaja"];

pub fn run(check: bool) -> Result<()> {
    let root = root();
    let committed = root.join("app/src/bindings");
    if check {
        let scratch = std::env::temp_dir().join(format!("navaja-bindings-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&scratch);
        generate(&root, &scratch)?;
        let problems = compare(&committed, &scratch)?;
        let _ = std::fs::remove_dir_all(&scratch);
        if !problems.is_empty() {
            eprintln!("bindings are stale; run `cargo xtask bindings` and commit the result");
        }
        report("xtask bindings --check", &problems)
    } else {
        if committed.exists() {
            std::fs::remove_dir_all(&committed)
                .with_context(|| format!("clearing {}", committed.display()))?;
        }
        generate(&root, &committed)?;
        println!("bindings written to {}", committed.display());
        Ok(())
    }
}

fn generate(root: &Path, out: &Path) -> Result<()> {
    let mut command = Command::new(cargo());
    command.current_dir(root).arg("test");
    for name in CRATES {
        command.args(["-p", name, "--features", &format!("{name}/ts")]);
    }
    // ts-rs emits one `export_bindings_*` test per exported type; run only those.
    command
        .args(["--lib", "export_bindings", "--", "--quiet"])
        .env("TS_RS_EXPORT_DIR", out);
    let status = command.status().context("running cargo test for ts-rs")?;
    if !status.success() {
        bail!("generating bindings failed ({status})");
    }
    Ok(())
}

/// Relative path -> contents with line endings normalised.
fn files(dir: &Path) -> Result<BTreeMap<PathBuf, String>> {
    let mut out = BTreeMap::new();
    if !dir.exists() {
        return Ok(out);
    }
    let mut stack = vec![dir.to_path_buf()];
    while let Some(current) = stack.pop() {
        for entry in
            std::fs::read_dir(&current).with_context(|| format!("reading {}", current.display()))?
        {
            let path = entry?.path();
            if path.is_dir() {
                stack.push(path);
            } else {
                let text = std::fs::read_to_string(&path)
                    .with_context(|| format!("reading {}", path.display()))?;
                let relative = path.strip_prefix(dir).unwrap_or(&path).to_path_buf();
                out.insert(relative, text.replace("\r\n", "\n"));
            }
        }
    }
    Ok(out)
}

fn compare(committed: &Path, fresh: &Path) -> Result<Vec<String>> {
    let old = files(committed)?;
    let new = files(fresh)?;
    let mut problems = Vec::new();
    for (path, text) in &new {
        match old.get(path) {
            None => problems.push(format!("missing: app/src/bindings/{}", path.display())),
            Some(existing) if existing != text => {
                problems.push(format!("out of date: app/src/bindings/{}", path.display()));
            }
            Some(_) => {}
        }
    }
    for path in old.keys().filter(|p| !new.contains_key(*p)) {
        problems.push(format!(
            "no longer generated: app/src/bindings/{}",
            path.display()
        ));
    }
    Ok(problems)
}
